name: osito_polar_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.1.2
  equatable: ^2.0.0
  dartz: ^0.10.1
  get_it: ^8.0.2
  app_links: ^6.4.1

  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8

  flutter_dotenv: ^5.1.0  # Para leer tu archivo .env
  url_launcher: ^6.3.0   # Para abrir la URL de Stripe en el navegador
  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/polarbear.png"
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # Aquí agregamos la carpeta de imágenes junto con tu .env
  assets:
    - .env
    - assets/images/