name: osito_polar_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Más compatible

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

  # --- ¡¡¡ESTA ES LA LÍNEA QUE FALTABA!!! ---
  # La necesitas para los puntos (●○) del carrusel
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true